src/admin_portal/urls.py
from django.urls import path
from . import views


app_name = 'admin_portal'
urlpatterns = [
    path('', views.AdminPortalView.as_view(), name='admin_portal'),
    path('order_status/<int:pk>', views.StatusView.as_view(), name="order_status"),
]

src/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('update_cart/', views.CartUpdate.as_view(), name='cart_update'),
    path('delete_good_in_cart/<int:pk>', views.DeleteGoodInCartView.as_view(), name='delete_good_in_cart'),
    path('', views.CartView.as_view(), name='cart_edit'),
]

src/catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"
urlpatterns = [
    path('', views.CatalogView.as_view(), name='catalog'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('genre_groups/', views.GenreGroup.as_view(), name='genre_groups'),
]

src/home_page/urls.py
from django.urls import path
from . import views

app_name = "home_page"
urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('login/', views.login_request, name='login'),
    path('register/', views.register_request, name='register'),
    path('logout/', views.logout_request, name= "logout"),
    path('shipping_info/', views.ShippingInfo.as_view(), name= "shipping_info"),
    path('about/', views.AboutCompany.as_view(), name= "about_info"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from catalog.views import SearchResultView

urlpatterns = [
    path("s-admin/", admin.site.urls),
    path('references/', include('references.urls', namespace="references")),
    path('product_card/', include('product_card.urls', namespace="product_card")),
    path('', include('home_page.urls', namespace="home_page")),
    path('catalog/', include('catalog.urls', namespace="catalog")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('carts/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('profile/', include('app_profiles.urls', namespace="profile")),
    path('admin_portal/', include('admin_portal.urls', namespace="admin_portal")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/references/urls.py
from django.urls import path
from . import views

app_name = "references"
urlpatterns = [

    #Authors URLs

    path('author_preview/<int:pk>/', views.ShowAuthor.as_view(), name='author_detail'),
    path('author_create/', views.CreateAuthor.as_view(), name='author_create'),
    path('author_update/<int:pk>/', views.UpdateAuthor.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', views.DeleteAuthor.as_view(), name='author_delete'),
    path('authors_list/', views.ShowAuthors.as_view(), name='authors_list'),

    #Series URLs

    path('series_preview/<int:pk>/', views.ShowSeries.as_view(), name='series_detail'),
    path('series_create/', views.CreateSeries.as_view(), name='series_create'),
    path('series_update/<int:pk>/', views.UpdateSeries.as_view(), name='series_update'),
    path('series_delete/<int:pk>/', views.DeleteSeries.as_view(), name='series_delete'),
    path('all_series_list/', views.ShowAllSeries.as_view(), name='series_list'),

    #Genres URLs

    path('genre_preview/<int:pk>/', views.ShowGenre.as_view(), name='genre_detail'),
    path('genre_create/', views.CreateGenre.as_view(), name='genre_create'),
    path('genre_update/<int:pk>/', views.UpdateGenre.as_view(), name='genre_update'),
    path('genre_delete/<int:pk>/', views.DeleteGenre.as_view(), name='genre_delete'),
    path('genres_list/', views.ShowGenres.as_view(), name='genres_list'),

    #Publishing houses URLs

    path('house_preview/<int:pk>/', views.ShowHouse.as_view(), name='house_detail'),
    path('house_create/', views.CreateHouse.as_view(), name='house_create'),
    path('house_update/<int:pk>/', views.UpdateHouse.as_view(), name='house_update'),
    path('house_delete/<int:pk>/', views.DeleteHouse.as_view(), name='house_delete'),
    path('houses_list/', views.ShowHouses.as_view(), name='houses_list')
]

src/catalog/models.py
from django.db import models
from django.utils import timezone
from product_card.models import Book
from django.contrib.auth.models import User
from django.contrib.auth.models import (
    AbstractBaseUser,
    UserManager,
    PermissionsMixin,
)


# Create your models here.

class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    username = models.ForeignKey(
        'AppUser', on_delete=models.CASCADE,
        related_name='user_name'
    )
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created_date']


class AppUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        unique=True,
        max_length=30,
    )

    email = models.EmailField()
    index = models.IntegerField(null=True)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    phone = models.IntegerField(help_text="Enter the number in international format.", null=True)
    country = models.CharField(null=True, max_length=30)
    city = models.CharField(null=True, max_length=30)
    address = models.CharField(null=True, max_length=60)
    reserve_address = models.CharField(blank=True, null=True, max_length=60)
    additional_info = models.CharField(blank=True, null=True, max_length=150)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    class Meta:
        verbose_name = 'username'
        verbose_name_plural = 'usernames'
        abstract = False

src/catalog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
            })
        }

src/catalog/views.py
from django.shortcuts import render
from django.views import generic, View
from product_card.models import Book
from django.core.paginator import Paginator
from .forms import CommentForm
from django.shortcuts import get_object_or_404, render
from .models import Comment
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q

# Create your views here.


class SearchResultView(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        results = ''
        if query:
            results = Book.objects.filter(
                Q(author__name__icontains=query) | Q(name__icontains=query) | Q(author__surname__icontains=query) | Q(genre__genre_name__icontains=query) | Q(series__book_series__icontains=query)
            ).distinct()
        paginator = Paginator(results, 12)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'catalog/search.html', context={
            'title': 'Search',
            'results': page_obj,
            'count': paginator.count,
        })


class CatalogView(View):

    def get(self, request, *args, **kwargs):
        book = Book.objects.all()
        paginator = Paginator(book, 12)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(
            request,
            'catalog/catalog.html',
            context={
                'page_obj': page_obj
            }
        )


class BookDetail(generic.DetailView):
    # template_name = 'catalog/book_detail.html'
    # model = Book
    # comment_form = CommentForm(request.POST)

    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs['pk'])
        last_posts = Book.objects.all().order_by('-id')[:3]
        comment_form = CommentForm()
        return render(request, 'catalog/book_detail.html', context={
            'book': book,
            'last_posts': last_posts,
            'comment_form': comment_form,
        })    

    
    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            text = request.POST['text']
            username = self.request.user
            book = get_object_or_404(Book, pk=kwargs['pk'])
            comment = Comment.objects.create(book=book, username=username,
                                             text=text)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
        return render(request, 'catalog/book_detail.html', context={
            'comment_form': comment_form
        })


class GenreGroup(View):

    def get(self, request, *args, **kwargs):
        genre_horror = Book.objects.filter(genre=1)
        genre_fantasy = Book.objects.filter(genre=3)
        genre_detective = Book.objects.filter(genre=4)
        genre_romance = Book.objects.filter(genre=5)
        genre_historical = Book.objects.filter(genre=6)
        return render(
            request,
            'catalog/genre_group.html',
            context={
                'genre_horror': genre_horror,
                'genre_fantasy': genre_fantasy,
                'genre_detective': genre_detective,
                'genre_romance': genre_romance,
                'genre_historical': genre_historical,
            }
        )

src/catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block title %}
{{ object.name }}
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h2>{{ book.name }}</h2>
    </div>
</div>
<div class="shadow p-3 mb-5 bg-body rounded">
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">{{ book.name }}</h2><br>
        <h4 class="featurette-heading fw-normal lh-1" >Price:<span class="text-muted"><em> {{ book.price }} BYN</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Author:<span class="text-muted"><em> {% for author in book.author.all %}{{ author }} {% endfor %}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Series:<span class="text-muted"><em> {{ book.series }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Genre:<span class="text-muted"><em> {% for genre in book.genre.all %}{{ genre }} {% endfor %}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Year:<span class="text-muted"><em> {{ book.publishing_year }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Pages:<span class="text-muted"><em> {{ book.pages }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Binding:<span class="text-muted"><em> {{ book.binding }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Format:<span class="text-muted"><em> {{ book.format }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >ISBN:<span class="text-muted"><em> {{ book.isbn }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Weight:<span class="text-muted"><em> {{ book.weight }} gr</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Age restriction:<span class="text-muted"><em> {{ book.age_restriction }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Publisher:<span class="text-muted"><em> {{ book.publishing_house }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Books available:<span class="text-muted"><em> {{ book.available_books }} pcs</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Available for purchase:<span class="text-muted"><em> {{ book.activity }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Rating:<span class="text-muted"><em> {{ book.rating }}</h4></em>
        
        <br>
        <h5 class="featurette-heading fw-normal lh-1" ><span class="text-muted"> {{ book.description }}</h5>
      </div>
      <div class="col-md-5 order-md-1">
        <img src="{{ book.image.url }}" width="500" height="500" border="1">
      </div>
    </div>
    <h6 class="featurette-heading fw-normal lh-1" >Changed:<span class="text-muted"><em> {{ book.modification_date }}</h6></em><br>

    
    <form action="{%url 'carts:cart_edit' %}" method="get">
      {% csrf_token %}
    <td><a href="{% url 'catalog:catalog' %}" class="btn btn-outline-secondary mb-3">Cancel</a></td> {% comment %}onclick="history.go(-1); return false; {% endcomment %}
    <td><button type="submit" class="btn btn-outline-success mb-3">Add to cart</button></td>
    <input type="hidden" name="book_pk" value="{{ book.pk }}">
    </form>
    <hr>
  </div>
    <div class="card my-4">
      <h5 class="card-header">Leave the comment:</h5>
      {% if user.is_authenticated %}
      <div class="card-body">
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  {{ comment_form.text }}
              </div>
              <br><button type="submit" class="btn btn-outline-primary">Save comment</button>
          </form>
      </div>
      {% else %}
      <h6 class="card-header"><a href="{% url 'home_page:login' %}?next={{ request.path }}">Login</a> or <a href="{% url 'home_page:register' %}?next={{ request.path }}">sign up</a> to leave the comment.</h6>
      {% endif %}
    </div>
    {% for comment in book.comments.all %}
    <div class="media mb-4">
      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
      <div class="media-body">
        <div class="shadow p-3 mb-5 bg-body rounded">
          <h5 class="mt-0">{{comment.username}}</h5>
          {{comment.text}}
        </div>
      </div>
    </div>
    {% endfor %}


{% endblock content %}

src/catalog/templates/catalog/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bs/js/bootstrap.min.js' %}"></script>
    <link href="{% static 'bs/css/custom_shop_products.css' %}" rel="stylesheet">


</head>
<body>
  
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">WAWBOOKS</a><br>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/catalog">Catalog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'catalog:genre_groups' %}">Genres</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'references:houses_list' %}">Publishing houses</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link active" href="{% url 'profile:profile_view' %}">Profile</a>
            {% endif %}
          </li>
          {% if perms.product_card.view_book%}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'admin_portal:admin_portal' %}">Administrative portal</a>
          </li>
          {% endif %}
        </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link"  href="https://select.by/kursy-valyut/natsbank-rb">2.4980 USD/BYN</a>
            </li>
          </ul>
        
          <form action="{% url 'search_results' %}" method="get" class="d-flex" role="search">
            <input name="q" type="text" class="form-control me-2" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success me-4" type="submit">Search</button>
          </form>

        <li style="list-style-type: none">
        {% if user.is_authenticated %}
  <span class="navbar-text mr-2">{{ user }}</span>
  <a href="/logout" class="btn btn-outline-light"><i class="bi bi-door-closed"></i></a>
{% else %}
  <a href="{% url 'home_page:login' %}" class="btn btn-outline-light">Login</i></a>
  <a href="{% url 'home_page:register' %}" class="btn btn-outline-light">Sign up</a>
{% endif %}
<a href="{% url 'carts:cart_edit' %}" class="btn btn-outline-light"><i class="bi bi-cart"></i></a>
        </li>
      </div>
    </div>
  </nav>
</header>

<main>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">A room without books is like a body without a soul.</h1>
      <p class="lead text-muted"> © Cicéron</p>
    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container size-fixed">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for obj in page_obj %}
      <div class="col">
        <div class="card shadow-sm">
           <img src="{{ obj.image.url }}" border="1" width="100%" height="500">
          <div class="card-body">
            <p class="card-text">{{ obj.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'catalog:book_detail' pk=obj.pk %}"  type="submit" class="btn btn-sm btn-outline-secondary">View</a>
                {% if perms.product_card.view_book%}
                <a href="{% url 'product_card:pc_update' pk=obj.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
</main>


<footer class="py-3 my-4">
  <div class="shadow p-3 mb-5 bg-body rounded">
  <div class="container">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="{%url 'home_page:shipping_info'%}" class="nav-link px-2 text-muted">Shipping</a></li>
      <li class="nav-item"><a href="{%url 'home_page:about_info'%}" class="nav-link px-2 text-muted">About</a></li>
      </ul>
    <p class="text-center text-muted">&copy; 2022 LeatherDiamond</p>
  </div>
  </div>
</footer>
</main>
</body>
</html>

src/catalog/templates/catalog/genre_group.html
{% extends "base.html" %}

{% block title %}
Available genres
{% endblock title %}

{% block content %}

<main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Immerse yourself in an exciting world of adventure!</h1>
          <p class="lead text-muted"> It's sure to please you.</p>
        </div>
      </div>
    </section>
    <div class="album py-5 bg-light">
      <div class="container size-fixed">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for genre_fantasy in genre_fantasy.all%}
          <div class="col">
            <div class="card shadow-sm">
               <img src="{{ genre_fantasy.image.url }}" border="1" width="100%" height="500">
              <div class="card-body">
                <p class="card-text">{{ genre_fantasy.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{% url 'catalog:book_detail' pk=genre_fantasy.pk %}"  type="submit" class="btn btn-sm btn-outline-secondary">View</a>
                    {% if perms.product_card.view_book%}
                    <a href="{% url 'product_card:pc_update' pk=genre_fantasy.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
</main>

<main>
      <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Mysterious stories and their denouements.</h1>
            <p class="lead text-muted"> The detective is definitely not going to be boring.</p>
          </div>
        </div>
      </section>
      <div class="album py-5 bg-light">
        <div class="container size-fixed">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for genre_detective in genre_detective.all%}
            <div class="col">
              <div class="card shadow-sm">
                 <img src="{{ genre_detective.image.url }}" border="1" width="100%" height="500">
                <div class="card-body">
                  <p class="card-text">{{ genre_detective.description }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="{% url 'catalog:book_detail' pk=genre_detective.pk %}"  type="submit" class="btn btn-sm btn-outline-secondary">View</a>
                      {% if perms.product_card.view_book%}
                      <a href="{% url 'product_card:pc_update' pk=genre_detective.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
</main>


<main>
        <section class="py-5 text-center container">
          <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
              <h1 class="fw-light">Immerse yourself in an unforgettable atmosphere of love and romance.</h1>
              <p class="lead text-muted"> Romantic books are just for you.</p>
            </div>
          </div>
        </section>
        <div class="album py-5 bg-light">
          <div class="container size-fixed">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
              {% for genre_romance in genre_romance.all%}
              <div class="col">
                <div class="card shadow-sm">
                   <img src="{{ genre_romance.image.url }}" border="1" width="100%" height="500">
                  <div class="card-body">
                    <p class="card-text">{{ genre_romance.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <a href="{% url 'catalog:book_detail' pk=genre_romance.pk %}"  type="submit" class="btn btn-sm btn-outline-secondary">View</a>
                        {% if perms.product_card.view_book%}
                        <a href="{% url 'product_card:pc_update' pk=genre_romance.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
</main>


<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Want to tickle your nerves and enjoy a book?</h1>
        <p class="lead text-muted"> Then this is the section for you.</p>
      </div>
    </div>
  </section>
  <div class="album py-5 bg-light">
    <div class="container size-fixed">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for genre_horror in genre_horror.all%}
        <div class="col">
          <div class="card shadow-sm">
             <img src="{{ genre_horror.image.url }}" border="1" width="100%" height="500">
            <div class="card-body">
              <p class="card-text">{{ genre_horror.description }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'catalog:book_detail' pk=genre_horror.pk %}"  type="submit" class="btn btn-sm btn-outline-secondary">View</a>
                  {% if perms.product_card.view_book%}
                  <a href="{% url 'product_card:pc_update' pk=genre_horror.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
</main>


<main>
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">You are fond of history books? You are welcome!</h1>
      <p class="lead text-muted"> Best history books are waiting for you.</p>
    </div>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container size-fixed">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for genre_historical in genre_historical.all%}
      <div class="col">
        <div class="card shadow-sm">
           <img src="{{ genre_historical.image.url }}" border="1" width="100%" height="500">
          <div class="card-body">
            <p class="card-text">{{ genre_historical.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'catalog:book_detail' pk=genre_historical.pk %}"  type="submit" class="btn btn-sm btn-outline-secondary">View</a>
                {% if perms.product_card.view_book%}
                <a href="{% url 'product_card:pc_update' pk=genre_historical.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
</main>
{% endblock content %}

src/catalog/templates/catalog/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Search{% endblock %}



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">

            <p class="lead">Results found: {{ count }}</p>
            {% for result in results %}
                <a href="{% url 'catalog:book_detail' pk=result.pk %}"><h2>{{ result.name }}</h2></a>
                Author: {% for author in result.author.all %}{{ author }} {% endfor %}<br>
                Genre: {% for genre in result.genre.all %}{{ genre }} {% endfor %}<br>
                Series: {{ result.series }}<br>
                Description: {{ result.description|safe }}
                <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block pagination %}
    <nav aria-label="Paginate me">
      <ul class="pagination justify-content-center">
        {% if results.has_previous %}
          <a class="page-link" href="?page={{ results.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" tabindex="-1">Previous</a>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link disabled" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for i in results.paginator.page_range %}
        {% if i == results.number %}
          <li class="page-item active"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if results.has_next %}
          <a class="page-link" href="?page={{ results.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <br>
{% endblock %}