src/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('update_cart/', views.CartUpdate.as_view(), name='cart_update'),
    path('delete_good_in_cart/<int:pk>', views.DeleteGoodInCartView.as_view(), name='delete_good_in_cart'),
    path('', views.CartView.as_view(), name='cart_edit'),
]

src/catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"
urlpatterns = [
    path('', views.CatalogView.as_view(), name='catalog'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('genre_groups/', views.GenreGroup.as_view(), name='genre_groups'),
]

src/home_page/urls.py
from django.urls import path
from . import views

app_name = "home_page"
urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('login/', views.login_request, name='login'),
    path('register/', views.register_request, name='register'),
    path('logout/', views.logout_request, name= "logout"),
    path('shipping_info/', views.ShippingInfo.as_view(), name= "shipping_info"),
    path('about/', views.AboutCompany.as_view(), name= "about_info"),
]

src/order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('create_order', views.CreateOrderView.as_view(), name="create_order"),
    path('success', views.success, name="success"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from catalog.views import SearchResultView

urlpatterns = [
    path("s-admin/", admin.site.urls),
    path('references/', include('references.urls', namespace="references")),
    path('product_card/', include('product_card.urls', namespace="product_card")),
    path('', include('home_page.urls', namespace="home_page")),
    path('catalog/', include('catalog.urls', namespace="catalog")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('carts/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('profile/', include('app_profiles.urls', namespace="profile")),
    path('admin_portal/', include('admin_portal.urls', namespace="admin_portal")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/order/models.py
from django.db import models
from django.contrib.sessions.models import Session
from carts.models import (
    Cart,
    BooksInCart,
)
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class CustomSession(Session):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE
    )

    class Meta:
        app_label = 'cart_id'


class Status(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Status"
        verbose_name_plural = "Statuses"


class Order(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='orders'
    )
    cart = models.OneToOneField(
        Cart,
        on_delete=models.PROTECT,
        verbose_name="Cart"
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT
    )
    contact_info = models.TextField(
        verbose_name="Contact info",
    )
    created = models.DateTimeField(
        verbose_name="Created",
        auto_now=False,
        auto_now_add=True
    )
    updated = models.DateTimeField(
        verbose_name="Updated",
        auto_now=True,
        auto_now_add=False
    )

    def __str__(self):
        return self.contact_info

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"

src/order/forms.py
from django import forms


class OrderCreateForm(forms.Form):
    contact_info = forms.CharField(
        label="Additional info",
        required=True,
        widget=forms.TextInput,
        help_text = "Please insert your delivery address and phone number if it's different from you account's data."
        )

src/order/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views import generic
from . import forms, models
from carts import models as carts_models
from django.urls import reverse_lazy
from trycourier import Courier

# Create your views here.


class CreateOrderView(generic.FormView):
    form_class = forms.OrderCreateForm
    template_name = 'order/create_order.html'
    success_url = reverse_lazy("order:success")

    def form_valid(self, form):
        cart_id = self.request.session.get('cart_id')
        cart, created = carts_models.Cart.objects.get_or_create(
            pk=cart_id,
            defaults={},
        )
        if created:
            return HttpResponseRedirect(reverse_lazy('carts:cart_edit'))
        info = form.cleaned_data.get('contact_info')
        status = models.Status.objects.get(pk=1)
        user = self.request.user
        order = models.Order.objects.update_or_create(
            cart=cart,
            contact_info=info,
            status=status,
            user=user,
        )
        client = Courier(auth_token="pk_prod_ZY5TQ360EZ42B4J8414GT35WD75B")
        resp = client.send_message(
            message={
                "to": {
                    "email": "customerservicewawbookspl@gmail.com"
          },
                "content": {
                "title": "New order",
                "body": "Hey! {{user}} {{email}} just placed a new order. Please check administrative portal to see details. {{link}}"
          },
          "data":{
            "user": user.name + ' ' + user.surname,
            "email": user.email,
            "link": 'https://alexanderdovguchits.pythonanywhere.com/admin_portal/'
          }
        }
      )
        self.request.session.delete('cart_id')
        if self.request.user.is_authenticated:
            cart_id = self.request.session.get('cart_id')
            customer1 = carts_models.Cart.objects.get(pk=cart_id)
            customer1.customer = self.request.user
            customer1.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id')
        cart, created = carts_models.Cart.objects.get_or_create(
            pk=cart_id,
            defaults={},
        )
        context['object'] = cart
        return context

    def get_success_url(self) -> str:
        del self.request.session['cart_id']
        return super().get_success_url()

def success(requsest):
    return render(requsest, 'order/success.html')

src/order/templates/order/create_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}   

{% block title %}Your cart{% endblock %}

{% block content %}
    <div>
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="text-center">
        <h1>Your cart</h1>
        </div>
        </div>
        <td><a href="{% url 'catalog:catalog' %}" class="btn btn-outline-secondary mb-3">Cancel</a></td>
        <div class="shadow p-3 mb-5 bg-body rounded">
        <form action="{% url 'carts:cart_update' %}" method="post">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Position</th>
                    <th scope="col">Good</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col">Options</th>
                </tr>
            </thead>
        </div>
            {% for good_in_cart in object.goods.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ good_in_cart.book.name }}</td>
                <td>
                    <div class="mb-2">
                        <input type="number" name="quantityforgood_{{good_in_cart.pk}}" min="1" step="1" class="form-control" value="{{good_in_cart.quantity}}">
                    </div>
                </td>
                <td>{{ good_in_cart.total_price }}</td>
                <td><form action="{% url 'carts:delete_good_in_cart' pk=good_in_cart.pk %}" method="post">{% csrf_token %}<button type="submit" class="btn btn-sm btn-outline-danger">Delete</button></form></td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="3">Total</td>
                <td>{{ object.total_price_cart }}</td>
                <td></td>
            </tr>
        </table>
            <button type="submit" name="submit" class="btn btn-outline-primary" value="save_cart">Save changes</button>
            {% if user.is_authenticated %}
            <button type="submit" name="submit" class="btn btn-outline-success" value="create_order">Order</button>
        </form>
    </div>
    {% else %}
    <td><a href="{% url 'home_page:register' %}" class="btn btn-outline-success">Order</a></td>
        {% endif %}
</div>
<div class="shadow p-3 mb-5 bg-body rounded">
<h1>Create the order in one step:</h1>
<form action="{% url 'order:create_order' %}" method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-success" >Create the order</button>
</form>
</div>
{% endblock %}

src/order/templates/order/success.html
{% extends "base.html" %}

{% block title %}Order created{% endblock %}

{% block content %}
<br>
    <h4>Your order was successfully created. Thank you.</h4>
    <h4>We will contact you soon to confirm the order details.</h4><br>
    <td><a href="{% url 'catalog:catalog' %}" class="btn btn-outline-secondary mb-3">Continue shopping</a></td>

{% endblock %}