src/admin_portal/urls.py
from django.urls import path
from . import views


app_name = 'admin_portal'
urlpatterns = [
    path('', views.AdminPortalView.as_view(), name='admin_portal'),
    path('order_status/<int:pk>', views.StatusView.as_view(), name="order_status"),
]

src/product_card/urls.py
from django.urls import path
from . import views

app_name = "product_card"
urlpatterns = [
    path('pc_preview/<int:pk>/', views.ShowProductCard.as_view(), name='pc_detail'),
    path('pc_create/', views.CreateProductCard.as_view(), name='pc_create'),
    path('pc_update/<int:pk>/', views.UpdateProductCard.as_view(), name='pc_update'),
    path('pc_delete/<int:pk>/', views.DeleteProductCard.as_view(), name='pc_delete'),
    path('pc_list/', views.ShowProductCardList.as_view(), name='pc_list'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from catalog.views import SearchResultView

urlpatterns = [
    path("s-admin/", admin.site.urls),
    path('references/', include('references.urls', namespace="references")),
    path('product_card/', include('product_card.urls', namespace="product_card")),
    path('', include('home_page.urls', namespace="home_page")),
    path('catalog/', include('catalog.urls', namespace="catalog")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('carts/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('profile/', include('app_profiles.urls', namespace="profile")),
    path('admin_portal/', include('admin_portal.urls', namespace="admin_portal")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/references/urls.py
from django.urls import path
from . import views

app_name = "references"
urlpatterns = [

    #Authors URLs

    path('author_preview/<int:pk>/', views.ShowAuthor.as_view(), name='author_detail'),
    path('author_create/', views.CreateAuthor.as_view(), name='author_create'),
    path('author_update/<int:pk>/', views.UpdateAuthor.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', views.DeleteAuthor.as_view(), name='author_delete'),
    path('authors_list/', views.ShowAuthors.as_view(), name='authors_list'),

    #Series URLs

    path('series_preview/<int:pk>/', views.ShowSeries.as_view(), name='series_detail'),
    path('series_create/', views.CreateSeries.as_view(), name='series_create'),
    path('series_update/<int:pk>/', views.UpdateSeries.as_view(), name='series_update'),
    path('series_delete/<int:pk>/', views.DeleteSeries.as_view(), name='series_delete'),
    path('all_series_list/', views.ShowAllSeries.as_view(), name='series_list'),

    #Genres URLs

    path('genre_preview/<int:pk>/', views.ShowGenre.as_view(), name='genre_detail'),
    path('genre_create/', views.CreateGenre.as_view(), name='genre_create'),
    path('genre_update/<int:pk>/', views.UpdateGenre.as_view(), name='genre_update'),
    path('genre_delete/<int:pk>/', views.DeleteGenre.as_view(), name='genre_delete'),
    path('genres_list/', views.ShowGenres.as_view(), name='genres_list'),

    #Publishing houses URLs

    path('house_preview/<int:pk>/', views.ShowHouse.as_view(), name='house_detail'),
    path('house_create/', views.CreateHouse.as_view(), name='house_create'),
    path('house_update/<int:pk>/', views.UpdateHouse.as_view(), name='house_update'),
    path('house_delete/<int:pk>/', views.DeleteHouse.as_view(), name='house_delete'),
    path('houses_list/', views.ShowHouses.as_view(), name='houses_list')
]

src/admin_portal/models.py
from django.db import models

# Create your models here.

src/admin_portal/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from order.models import (
    Order,
    Status,
)
from django.http import (
    HttpResponseRedirect,
)
from django.shortcuts import (
    get_object_or_404,
    render,
)
from django.urls import reverse_lazy
from django.views import generic
# from admin_portal.forms import PortalForm

# Create your views here.

class AdminPortalView(LoginRequiredMixin, PermissionRequiredMixin, generic.TemplateView):
    permission_required = 'product_card.view_book'
    login_url = 'home_page:login'

    def get(self, request, *args, **kwargs):
        return render(
            request, 'admin_portal/portal_detail.html', context={
                'user': request.user,
                'orders': Order.objects.select_related('cart'),
                'status_created' : Status.objects.get(pk=1),
                'status_updated' : Status.objects.get(pk=2),
                'status_cancelled' : Status.objects.get(pk=3),
            }
        )


class StatusView(generic.UpdateView):
    def post(self, request, *args, **kwargs):
        pk = kwargs["pk"]
        order = get_object_or_404(Order, pk=pk)
        status = self.request.POST.get('status')
        order.status_id = status
        order.save()
        return HttpResponseRedirect(reverse_lazy('admin_portal:admin_portal'))

src/admin_portal/templates/admin_portal/portal_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Administrative portal
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h2>Welcome to administrative portal, {{ user }}!</h2>
    </div>
</div>

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            <i class="bi bi-1-circle"> <strong>List of available authors.</strong></i> 
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            Here you can see the list of authors and change it.<br>
            <strong>Click the button to start.</strong><br>
            <br>
            <a href="{%url 'references:authors_list'%}" class="btn btn-outline-success mb-3">Show the list of authors</a>
          </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <i class="bi bi-2-circle"> <strong>List of available book genres.</strong></i>
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            Find below the list of book genres available in store and change it if you need it.<br>
            <strong>Click the button to start.</strong><br>
            <br>
            <a href="{%url 'references:genres_list'%}" class="btn btn-outline-success mb-3">Show the list of genres</a>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        <i class="bi bi-3-circle"> <strong>List of available book series.</strong></i>
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            Find below the list of book series available in store and change it if you need it.<br>
            <strong>Click the button to start.</strong><br>
            <br>
            <a href="{%url 'references:series_list'%}" class="btn btn-outline-success mb-3">Show the list of series</a>
        </div>
      </div>
    </div>
  
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
    <i class="bi bi-4-circle"> <strong>List of available publishers.</strong></i>
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          Find below the list of publishers and change it if you need it.<br>
          <strong>Click the button to start.</strong><br>
          <br>
          <a href="{%url 'references:houses_list'%}" class="btn btn-outline-success mb-3">Show the list of publishers</a>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFive">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
    <i class="bi bi-5-circle"> <strong>List of available books.</strong></i>
      </button>
    </h2>
    <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          Find below the list of books that are available in store and change it if you need it. You also can change the book directly from catalog.<br>
          <strong>Click the button to start.</strong><br>
          <br>
          <a href="{%url 'product_card:pc_list'%}" class="btn btn-outline-success mb-3">Show the list of books</a>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingSix">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="true" aria-controls="collapseSix">
    <i class="bi bi-6-circle"> <strong>List of orders.</strong></i>
      </button>
    </h2>
    <div id="collapseSix" class="accordion-collapse collapse show" aria-labelledby="headingSix" data-bs-parent="#accordionExample">
      <div class="accordion-body">

          <hr class="featurette-divider">
          <div class="text-center">
            <h2>Orders:</h2>
          </div>
          <hr class="featurette-divider">
          <div class="table-responsive">
            <div class="text-center">
              <table class="table table-striped table-hover">
                <thead>
                <tr>
                  <th scope="col">Order Nr</th>
                  <th scope="col">Customer</th>
                  <th scope="col">Goods</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Total price</th>
                  <th scope="col">Customer additions</th>
                  <th scope="col">Created</th>
                  <th scope="col">Updated</th>
                  <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
        {% for order in orders %}
        <div class="container">
          <tr>
            <td>{{ order.id }}
            <td>{{ order.user }}
              <hr class="featurette-divider">
              <button class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#id{{order.user.pk}}">More</button>
            </td>
            
            <div class="modal fade" id="id{{order.user.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-scrollable">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Customer info:</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <div class="row featurette">
                    <div class="container">
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>Name and surname:</strong><span class="text-muted"><em> {{ order.user.name }} {{ order.user.surname }}</h5></em>
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>Email:</strong><span class="text-muted"><em> {{ order.user.email }}</h5></em>
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>Phone number:</strong><span class="text-muted"><em> {{ order.user.phone }}</h5></em>
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>Country:</strong><span class="text-muted"><em> {{ order.user.country }}</h5></em>
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>City:</strong><span class="text-muted"><em> {{ order.user.city }}</h5></em>
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>Index:</strong><span class="text-muted"><em> {{ order.user.index }}</h5></em>
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>Address:</strong><span class="text-muted"><em> {{ order.user.address }}</h5></em>
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>Reserve address:</strong><span class="text-muted"><em> {{ order.user.reserve_address|default:'No reserve address was provided.' }}</h5></em>
                      <h5 class="featurette-heading fw-normal lh-1" > <strong>Additional info:</strong><span class="text-muted"><em> {{ order.user.additional_info|default:'No additional info was provided.' }}</h5></em>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
                  </div>
                </div>
              </div>
            </div>
            <td>{{ order.cart.book_names_cart }}</td>
            <td>{{ order.cart.total_quantity_cart }}</td>
            <td>{{ order.cart.total_price_cart }}</td>
            <td>{{ order.contact_info }}</td>
            <td>{{ order.created }}</td>
            <td>{{ order.updated }}</td>
            <td>

              <form method="POST" action="{% url 'admin_portal:order_status' order.id %}">
                {% csrf_token %}
                <div class="container">
                  <select name="status" class="form-control">
                    {% if order.status_id == status_created.id %}
                    <option value="{{ 1 }}" selected>{{ status_created }}</option>
                    <option value="{{ 2 }}">{{ status_updated }}</option>
                    <option value="{{ 3 }}">{{ status_cancelled }}</option>
                    {% endif %}
                    {% if order.status_id == status_updated.id %}
                    <option value="{{ 1 }}" >{{ status_created }}</option>
                    <option value="{{ 2 }}" selected>{{ status_updated }}</option>
                    <option value="{{ 3 }}">{{ status_cancelled }}</option>
                    {% endif %}
                    {% if order.status_id == status_cancelled.id %}
                    <option value="{{ 1 }}">{{ status_created }}</option>
                    <option value="{{ 2 }}">{{ status_updated }}</option>
                    <option value="{{ 3 }}" selected>{{ status_cancelled }}</option>
                    {% endif %}
                  </select>
                <hr class="featurette-divider">
                <input type="submit" name="submit" value="Update status" class="btn btn-outline-success mb-3">
              
                </div>
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
      </div>
    </div>
  </div>
</div>

  
{% endblock content %}