src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from catalog.views import SearchResultView

urlpatterns = [
    path("s-admin/", admin.site.urls),
    path('references/', include('references.urls', namespace="references")),
    path('product_card/', include('product_card.urls', namespace="product_card")),
    path('', include('home_page.urls', namespace="home_page")),
    path('catalog/', include('catalog.urls', namespace="catalog")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('carts/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('profile/', include('app_profiles.urls', namespace="profile")),
    path('admin_portal/', include('admin_portal.urls', namespace="admin_portal")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/references/urls.py
from django.urls import path
from . import views

app_name = "references"
urlpatterns = [

    #Authors URLs

    path('author_preview/<int:pk>/', views.ShowAuthor.as_view(), name='author_detail'),
    path('author_create/', views.CreateAuthor.as_view(), name='author_create'),
    path('author_update/<int:pk>/', views.UpdateAuthor.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', views.DeleteAuthor.as_view(), name='author_delete'),
    path('authors_list/', views.ShowAuthors.as_view(), name='authors_list'),

    #Series URLs

    path('series_preview/<int:pk>/', views.ShowSeries.as_view(), name='series_detail'),
    path('series_create/', views.CreateSeries.as_view(), name='series_create'),
    path('series_update/<int:pk>/', views.UpdateSeries.as_view(), name='series_update'),
    path('series_delete/<int:pk>/', views.DeleteSeries.as_view(), name='series_delete'),
    path('all_series_list/', views.ShowAllSeries.as_view(), name='series_list'),

    #Genres URLs

    path('genre_preview/<int:pk>/', views.ShowGenre.as_view(), name='genre_detail'),
    path('genre_create/', views.CreateGenre.as_view(), name='genre_create'),
    path('genre_update/<int:pk>/', views.UpdateGenre.as_view(), name='genre_update'),
    path('genre_delete/<int:pk>/', views.DeleteGenre.as_view(), name='genre_delete'),
    path('genres_list/', views.ShowGenres.as_view(), name='genres_list'),

    #Publishing houses URLs

    path('house_preview/<int:pk>/', views.ShowHouse.as_view(), name='house_detail'),
    path('house_create/', views.CreateHouse.as_view(), name='house_create'),
    path('house_update/<int:pk>/', views.UpdateHouse.as_view(), name='house_update'),
    path('house_delete/<int:pk>/', views.DeleteHouse.as_view(), name='house_delete'),
    path('houses_list/', views.ShowHouses.as_view(), name='houses_list')
]

src/references/models.py
from django.db import models
from django.urls import reverse_lazy

# Create your models here.

class BookAuthor(models.Model):
    name = models.CharField(
       max_length=30,
       verbose_name="Author's name",
    )
    surname = models.CharField(
       max_length=30,
       verbose_name="Author's surname",
    )
    description = models.TextField(
        blank=True,
        null=True
    )

    def get_absolute_url(self):
        return reverse_lazy('references:author_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' ' + self.surname


class BookSeries(models.Model):
    book_series = models.CharField(
        max_length=30,
        verbose_name="Books in series",
    )
    description = models.TextField(
        blank = True,
        null = True
    )

    def get_absolute_url(self):
        return reverse_lazy('references:series_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.book_series)


class BookGenre(models.Model):
    genre_name = models.CharField(
        max_length=30,
        verbose_name="Genre"
    )
    description = models.TextField(
        blank=True,
        null=True
    )

    def get_absolute_url(self):
        return reverse_lazy('references:genre_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.genre_name


class BookPublishingHouse(models.Model):
    house_name = models.CharField(
        max_length=30,
        verbose_name="Publishing house"
    )
    description = models.TextField(
        blank=True,
        null=True
    )

    def get_absolute_url(self):
        return reverse_lazy('references:house_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.house_name

    

src/references/forms.py
from django import forms
from . import models

#Forms for references

class AuthorForm(forms.ModelForm):
    class Meta:
        model = models.BookAuthor
        fields = ['name', 'surname', 'description']


class SeriesForm(forms.ModelForm):
    class Meta:
        model = models.BookSeries
        fields = ['book_series', 'description']


class GenreForm(forms.ModelForm):
    class Meta:
        model = models.BookGenre
        fields = ['genre_name', 'description']


class PublishingHouseForm(forms.ModelForm):
    class Meta:
        model = models.BookPublishingHouse
        fields = ['house_name', 'description']

src/references/views.py
from . import models, forms
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.

#CBV for Author model.

class ShowAuthors(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    login_url = 'home_page:login'
    permission_required = 'references.view_bookauthor'
    model = models.BookAuthor
    template_name = 'references/list_author.html'


class ShowAuthor(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    model = models.BookAuthor
    login_url = 'home_page:login'
    permission_required = 'references.view_bookauthor'
    template_name = 'references/detail_author.html'


class CreateAuthor(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = 'home_page:login'
    permission_required = 'references.add_bookauthor'
    model = models.BookAuthor
    form_class = forms.AuthorForm
    template_name = 'references/edit_author.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Create'
        return context


class UpdateAuthor(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = 'home_page:login'
    permission_required = 'references.change_bookauthor'
    model = models.BookAuthor
    form_class = forms.AuthorForm
    template_name = 'references/edit_author.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Update'
        return context


class DeleteAuthor(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = 'home_page:login'
    permission_required = 'references.delete_bookauthor'
    model = models.BookAuthor
    template_name = 'references/delete_author.html'

    def get_success_url(self):
        return reverse_lazy('references:authors_list')

#CBV for Series model.

class ShowAllSeries(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    login_url = 'home_page:login'
    permission_required = 'references.view_bookseries'
    model = models.BookSeries
    template_name = 'references/list_series.html'


class ShowSeries(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    login_url = 'home_page:login'
    permission_required = 'references.view_bookseries'
    model = models.BookSeries
    template_name = 'references/detail_series.html'


class CreateSeries(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = 'home_page:login'
    permission_required = 'references.add_bookseries'
    model = models.BookSeries
    form_class = forms.SeriesForm
    template_name = 'references/edit_series.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Create'
        return context


class UpdateSeries(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = 'home_page:login'
    permission_required = 'references.change_bookseries'
    model = models.BookSeries
    form_class = forms.SeriesForm
    template_name = 'references/edit_series.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Update'
        return context


class DeleteSeries(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = 'home_page:login'
    permission_required = 'references.delete_bookseries'
    model = models.BookSeries
    template_name = 'references/delete_series.html'

    def get_success_url(self):
        return reverse_lazy('references:series_list')

#CBV for Genre model.

class ShowGenres(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    login_url = 'home_page:login'
    permission_required = 'references.view_bookgenre'
    model = models.BookGenre
    template_name = 'references/list_genre.html'


class ShowGenre(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    login_url = 'home_page:login'
    permission_required = 'references.view_bookgenre'
    model = models.BookGenre
    template_name = 'references/detail_genre.html'


class CreateGenre(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = 'home_page:login'
    permission_required = 'references.add_bookgenre'
    model = models.BookGenre
    form_class = forms.GenreForm
    template_name = 'references/edit_genre.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Create'
        return context


class UpdateGenre(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = 'home_page:login'
    permission_required = 'references.change_bookgenre'
    model = models.BookGenre
    form_class = forms.GenreForm
    template_name = 'references/edit_genre.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Update'
        return context


class DeleteGenre(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = 'home_page:login'
    permission_required = 'references.delete_bookgenre'
    model = models.BookGenre
    template_name = 'references/delete_genre.html'

    def get_success_url(self):
        return reverse_lazy('references:genres_list')

#CBV Publishing house form.

class ShowHouses(generic.ListView):
    login_url = 'home_page:login'
    model = models.BookPublishingHouse
    template_name = 'references/list_house.html'


class ShowHouse(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    login_url = 'home_page:login'
    permission_required = 'references.view_bookpublishinghouse'
    model = models.BookPublishingHouse
    template_name = 'references/detail_house.html'


class CreateHouse(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = 'home_page:login'
    permission_required = 'references.add_bookpublishinghouse'
    model = models.BookPublishingHouse
    form_class = forms.PublishingHouseForm
    template_name = 'references/edit_house.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Create'
        return context


class UpdateHouse(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = 'home_page:login'
    permission_required = 'references.change_bookpublishinghouse'
    model = models.BookPublishingHouse
    form_class = forms.PublishingHouseForm
    template_name = 'references/edit_house.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Update'
        return context


class DeleteHouse(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = 'home_page:login'
    permission_required = 'references.delete_bookpublishinghouse'
    model = models.BookPublishingHouse
    template_name = 'references/delete_house.html'

    def get_success_url(self):
        return reverse_lazy('references:houses_list')

src/references/templates/references/create_genre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create genre</title>
</head>
<body>
    <h1>Please create book's genre</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

src/references/templates/references/create_series.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create series</title>
</head>
<body>
    <h1>Please create book's series</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

src/references/templates/references/delete_author.html
{% extends "base.html" %}

{% block title %}
Delete author
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>Are you sure that you want to delete the author?</h1><br>
</div>
</div>
<p>Author <b>"{{ object.name }} {{ object.surname}}"</b> will be permanently deleted from the list.<br>
    If you are agree please click delete button.</p><br>
    Description: {{ object.description|default:"No description was provided" }}<br>
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'references:authors_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

src/references/templates/references/delete_genre.html
{% extends "base.html" %}

{% block title %}
Delete genre
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>Are you sure that you want to delete the genre?</h1><br>
    </div>
    </div>
    <p>Genre <b>"{{ object.genre_name }}"</b> will be permanently deleted from the list.<br>
        If you are agree please click delete button.</p><br>
        Description: {{ object.description|default:"No description was provided" }}<br>
        <br>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'references:genres_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

src/references/templates/references/delete_house.html
{% extends "base.html" %}

{% block title %}
Delete publishing house
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>Are you sure that you want to delete the publisher?</h1><br>
    </div>
    </div>
    <p>Publishing house <b>"{{ object.house_name }}"</b> will be permanently deleted from the list.<br>
        If you are agree please click delete button.</p><br>
        Description: {{ object.description|default:"No description was provided" }}<br>
        <br>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'references:houses_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

src/references/templates/references/delete_series.html
{% extends "base.html" %}

{% block title %}
Delete series
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>Are you sure that you want to delete the series?</h1><br>
    </div>
    </div>
    <p>Book's series <b>"{{ object.book_series }}"</b> will be permanently deleted from the list.<br>
        If you are agree please click delete button.</p><br>
        Description: {{ object.description|default:"No description was provided" }}<br>
        <br>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'references:series_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

src/references/templates/references/detail_author.html
{% extends "base.html" %}

{% block title %}
Author's preview
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1><span style="color: green;">Author successfully created!</span></h1>
    </div>
    </div>
    Author's data: <b>"{{ object.name }} {{object.surname}}"</b><br>
    Description: {{ object.description|default:"No description was provided" }}<br>
    <br>
    <td><a href="{% url 'references:author_create' %}" class="btn btn-outline-success mb-3">Create a new author</a></td>
    <br>
    <td><a href="{% url 'references:authors_list' %}" class="btn btn-outline-success mb-3">Show the list of authors</a></td>
{% endblock content %}

src/references/templates/references/edit_genre.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{ operation_name }} genre
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>{{ operation_name }} book's genre</h1>
</div>
</div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'references:genres_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Save changes" class="btn btn-success">
    </form>
{% endblock content %}

src/references/templates/references/edit_house.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{ operation_name }} publishing house
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>{{ operation_name }} the publishing house</h1>
</div>
</div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'references:houses_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Save changes" class="btn btn-success">
    </form>
{% endblock content %}

src/references/templates/references/edit_series.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{ operation_name }} series
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>{{ operation_name }} book's series</h1>
</div>
</div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'references:series_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Save changes" class="btn btn-success">
    </form>
{% endblock content %}

src/references/templates/references/list_genre.html
{% extends "base.html" %}

{% block title %}List of genres{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>List of genres</h1>
    </div>
    </div>
        <td><a href="{% url 'references:genre_create' %}" class="btn btn-outline-success mb-3">Create a new genre</a></td>
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="table-responsive">
        <div class="text-center">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col">Genre name</th>
                  <th scope="col">Options</th>
                </tr>
              </thead>
            <tbody>
        {% for obj in object_list %}
        <tr>
            <td>{{ obj.genre_name }}</td>
            <td><a href="{% url 'references:genre_update' pk=obj.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'references:genre_delete' pk=obj.pk %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#id{{obj.pk}}"><i class="bi bi-x-lg"></i></a></td>
        </tr>
                <!-- Modal -->
<div class="modal fade" id="id{{obj.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure that you want to delete the genre?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Genre <b>"{{ obj.genre_name }}"</b> will be permanently deleted from the list.
            If you are agree please click delete button.<br>
            <br>
            <form action="{% url 'references:genre_delete' pk=obj.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
        </div>
      </div>
    </div>
  </div>
            </tbody>
        </div>
        {% endfor %}
        </table>
{% endblock content %}

src/references/templates/references/list_house.html
{% extends "base.html" %}

{% block title %}List of houses{% endblock title %}


{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>List of publishing houses</h1>
    </div>
    </div>
    {% if perms.references.view_bookpublishinghouse %}
        <td><a href="{% url 'references:house_create' %}" class="btn btn-outline-success mb-3">Create a new publishing house</a></td>
      {% endif %}
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="table-responsive">
        <div class="text-center">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col">Publishing house</th>
                  {% if perms.references.view_bookpublishinghouse %}
                  <th scope="col">Options</th>
                  {% endif %}
                </tr>
              </thead>
            <tbody>
        {% for obj in object_list %}
        <tr>
            <td>{{ obj.house_name }}</td>
            {% if perms.references.view_bookpublishinghouse %}
            <td><a href="{% url 'references:house_update' pk=obj.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'references:house_delete' pk=obj.pk %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#id{{obj.pk}}"><i class="bi bi-x-lg"></i></a></td>
              {% endif %}
              </tr>
                <!-- Modal -->
<div class="modal fade" id="id{{obj.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure that you want to delete the publisher?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Publishing house <b>"{{ obj.house_name }}"</b> will be permanently deleted from the list.
            If you are agree please click delete button.<br>
            <br>
            <form action="{% url 'references:house_delete' pk=obj.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
        </div>
      </div>
    </div>
  </div>
            </tbody>
        </div>
        {% endfor %}
        </table>
{% endblock content %}

src/references/templates/references/list_series.html
{% extends "base.html" %}

{% block title %}List of series{% endblock title %}


{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>List of series</h1>
    </div>
    </div>
        <td><a href="{% url 'references:series_create' %}" class="btn btn-outline-success mb-3">Create a new series</a></td>
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="table-responsive">
        <div class="text-center">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col">Series</th>
                  <th scope="col">Options</th>
                </tr>
              </thead>
            <tbody>
        {% for obj in object_list %}
        <tr>
            <td>{{ obj.book_series }}</td>
            <td><a href="{% url 'references:series_update' pk=obj.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'references:series_delete' pk=obj.pk %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#id{{obj.pk}}"><i class="bi bi-x-lg"></i></a></td>
        </tr>
                <!-- Modal -->
<div class="modal fade" id="id{{obj.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure that you want to delete the series?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Series <b>"{{ obj.book_series }}"</b> will be permanently deleted from the list.
            If you are agree please click delete button.<br>
            <br>
            <form action="{% url 'references:series_delete' pk=obj.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
        </div>
      </div>
    </div>
  </div>
            </tbody>
        </div>
        {% endfor %}
        </table>
        {% endblock content %}

src/references/templates/references/update_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Please update the author's data</title>
</head>
<body>
    <h1>Please create book's author</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>